spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cecafes
    username: postgres
    password: gugu
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
    context-path: /

auth-api:
  username: admin
  password: admin